import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button/Button.js'
import Header from '../components/Header/Header.js'
import Card from '../components/Card/Card.js'
import ProblemList from '../components/ProblemList/ProblemList.js'
import StatCard from '../components/StatCard/StatCard.js'
import PageTitle from '../components/PageTitle/PageTitle.js'
import DateComponent from '../components/DateComponent/DateComponent.js'
import ProgressCalendar from '../components/ProgressCalendar/ProgressCalendar.js'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useAuth } from '../config/authContext'
import Counter from './Counter.js'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const { user, login } = useAuth()

  const testButtonHandler = () => {
    console.log("button succeeds")
  }

  return (
    <>
      <Head>
        <title>it's time to leetcode</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className={styles.description}>
        
            <Button handlerFunction={testButtonHandler} buttonText={"test button"} />
          
          
        </div> */}

        <div className={styles.bodyoutline}>
          <Header />
          <Counter id={user === undefined ? "" : user.uid} />
          <DateComponent /> 
          <div className={styles.cTestOne}>
            {/* <Card title="testing">
              la di da
            </Card> */}
            <ProgressCalendar />

          </div>
          <div className={styles.stat}>
            <StatCard number="(ó﹏ò｡)" />
            <StatCard number="60" label="completed"/>


          </div>
          <div className={styles.cTest}>
            {/* <Card title="testing">
              la di da
            </Card> */}
            <ProblemList />

          </div>
          
        </div>
        <div className={styles.bottom}>
          <PageTitle title="HOME" />

        </div>
        {/* <div className={styles.center}>
          
        </div> */}

        
      </main>
     
    </>
  )
}
